[32m[I 2025-05-27 00:27:38,920][0m A new study created in memory with name: no-name-64532442-f0a0-4d7a-aca9-22fa6262266c[0m
[33m[W 2025-05-27 00:27:38,934][0m Trial 0 failed with parameters: {'n_estimators': 601, 'learning_rate': 0.04824897415114414, 'max_depth': 7, 'subsample': 0.7322664244814417, 'colsample_bytree': 0.7255753966537457, 'gamma': 3.5642901386823915, 'min_child_weight': 2} because of the following error: TypeError("XGBClassifier.fit() got an unexpected keyword argument 'eval_metric'").[0m
Traceback (most recent call last):
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "c:\Users\PC\Desktop\Works\ML\ML-Competition\ML-Competition\smoker_status\competition.py", line 78, in objective
    model.fit(X_train, y_train,
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\xgboost\core.py", line 729, in inner_f
    return func(**kwargs)
TypeError: XGBClassifier.fit() got an unexpected keyword argument 'eval_metric'
[33m[W 2025-05-27 00:27:38,936][0m Trial 0 failed with value None.[0m
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\Works\ML\ML-Competition\ML-Competition\smoker_status\competition.py", line 91, in <module>
    study.optimize(objective, n_trials=30)
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\optuna\study\study.py", line 475, in optimize
    _optimize(
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\optuna\study\_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\optuna\study\_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\optuna\study\_optimize.py", line 248, in _run_trial
    raise func_err
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "c:\Users\PC\Desktop\Works\ML\ML-Competition\ML-Competition\smoker_status\competition.py", line 78, in objective
    model.fit(X_train, y_train,
  File "C:\Users\PC\anaconda3\envs\smoker-ml\lib\site-packages\xgboost\core.py", line 729, in inner_f
    return func(**kwargs)
TypeError: XGBClassifier.fit() got an unexpected keyword argument 'eval_metric'
